feat(gh-009): fix the yaml

diff --git a/.github/workflows/09-functions.yaml b/.github/workflows/09-functions.yaml
--- a/.github/workflows/09-functions.yaml
+++ b/.github/workflows/09-functions.yaml
@@ -1,32 +1,27 @@
 name: "09 - Using Functions."
 on:
-    pull_request:
-    workflow_dispatch:
+  pull_request:
+  workflow_dispatch:
 
 jobs:
-    echo1:
-        runs-on: ubuntu-latest
-        steps:
-            - name: "Failing step, should exit with a non-zero code"
-              id: "fail-step"
-              run: exit 1
-            
-            - name: "I will be skipped"
-              id: skip-step
-              if: steps.fail-step.outcome == 'success'
-              run: echo "I will print if previous steps succeed."
-            
-            - name: "I will execute"
-              if: steps.fail-step.outcome == 'failure' || steps.skip-step.outcome == 'failure'
-              id: execute-step
-              run: echo "I will print if any previous step fails"
-            
-            - name: "I will execute"
-              id: execute-step-2
-              if: ${{ !cancelled() }}
-              run: echo "I will always print, except when the workflow is cancelled."
-            
-            - name: "I will execute when cancelled"
-              id: execute-step-3
-              if: cancelled()
-              run: echo "I will execute when cancelled"
+  echo1:
+    runs-on: ubuntu-latest
+    steps:
+      - name: "Failing step, should exit with a non-zero code"
+        run: exit 1
+
+      - name: "I will be skipped"
+        if: ${{ success() }}
+        run: echo "I will print if previous steps succeed."
+
+      - name: "I will execute"
+        if: ${{ failure() }}
+        run: echo "I will print if any previous step fails"
+
+      - name: "I will execute"
+        if: ${{ !cancelled() }}
+        run: echo "I will always print, except when the workflow is cancelled."
+
+      - name: "I will execute when cancelled"
+        if: ${{ cancelled() }}
+        run: echo "I will execute when cancelled"
